# Generated by Django 5.1.2 on 2024-11-05 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('PISTOLA', 'Pistola'), ('FUZIL', 'Fuzil'), ('RIFLE', 'Rifle'), ('SNIPER', 'Sniper'), ('SUBMETRALHADORA', 'Submetralhadora'), ('LMG', 'LMG'), ('ESCOPETA', 'Escopeta'), ('ARMA_BRANCA', 'Arma Branca')], max_length=20)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='armas')),
            ],
        ),
        migrations.CreateModel(
            name='Mapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='mapas')),
            ],
        ),
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=155)),
                ('habilidades', models.CharField(max_length=255)),
                ('funcao', models.CharField(choices=[('DUELISTA', 'Duelista'), ('INICIADOR', 'Iniciador'), ('CONTROLADOR', 'Controlador'), ('SENTINELA', 'Sentinela')], max_length=50)),
                ('sexo', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino')], max_length=10)),
                ('origem', models.CharField(max_length=255)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='personagens')),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placar_time_1', models.IntegerField()),
                ('placar_time_2', models.IntegerField()),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('mapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valorant_app.mapa')),
                ('personagem', models.ManyToManyField(to='valorant_app.personagem')),
            ],
        ),
    ]
